### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by g8orgir1** [medokin/soundpad-text-to-speech#16] opened 2020-07-15 23:08 UTC
When typing something, the words are not played when entered and the "Play in Soundpad" button stops working.

**Comment by ashenbeauty** [comment] 2020-07-16 00:31
I have the same issue. This seems to be related to the recent SoundPad 3.3.0 update. I hope Medokin is able to fix this bug, although this tool seems to be somewhat graveyarded.

**Comment by medokin** [comment] 2020-07-16 06:30
Duplicate of #15

**Closed as completed by medokin** 2020-07-16 06:30 UTC

**Comment by medokin** [comment] 2020-07-16 06:46
@kingcailan It is not graveyarded 🤪 Just because I am not pumping features, does not mean that it is not maintained.

**Comment by ashenbeauty** [comment] 2020-07-16 08:24
Understood! I tend to assume a project is dead or finished when noone shares bugs, and there are no commits. Sorry for the assumption!
